### PR TITLE
8.0 Add support for multiple copies

### PR DESCRIPTION
**Pull request by alexis-via**

### CODE REVIEW

**Comment by alexis-via** [comment]
This has been successfully tested on the Cups server of my Laptop running Ubuntu with my home printer.

**Comment by rvalyi** [comment]
:+1:  LGTM

**Comment by pedrobaeza** [comment]
@gurneyalex, can you add cups module to runbot instance?

For this, :+1:

**Comment by lmignon** [comment]
:+1:

**Comment by yvaucher** [comment]
:+1: merging

**Pull request merged**
