### PR TITLE
[9.0][MIG] printer_tray

### PR DESCRIPTION
**Pull request by Garamotte**
Migration of the printer_tray module to version 9.0.

This PR includes two other PRs.
I'll rebase this branch when the other PRs are merged:
- [x] https://github.com/OCA/report-print-send/pull/64 : Add unit tests on the printer_tray module on v8.0
- [x] https://github.com/OCA/report-print-send/pull/60 : Improvement of the base_report_to_printer module

### CODE REVIEW

**Comment by lasley** [comment]
Good to rebase @sylvain-garancher

**Comment by Garamotte** [comment]
@lasley Rebase done.
You can replace the WIP label by Needs Review.

**Review by lasley — APPROVED** [review]
Wow I have no suggestions. Great job @sylvain-garancher

**Review by pedrobaeza — APPROVED** [review]
OK, I think this one is good to go

**Pull request merged**
