### PR TITLE
[ADD] base_report_to_qz: new module to print with QZ Tray

### PR DESCRIPTION
**Pull request by chrisandrewmann**
Originally created by @angelmoya for V14 ref: https://github.com/OCA/report-print-send/pull/270
Migrated to 16.0 with changes noted below.

---

Module works, but could be nice to improve.

I push because I think that module could be good alternative to base report_to_printer, and maybe someone wants to colaborate.

QZ Tray allow to print over html, this way users can use local printers with Odoo.

You can install QZ Tray on Linux, Windows or Mac computer, and I'm not sure, but I read about use with android.

QZ Tray is LGPL 2.1 licensed, you can buy support to get certificates, but you can use your own certificates.

On Install.md I try to explain how to install, you need generate your own certificate, an configure in Odoo and QZ Tray.

Module works, but as I said it could be improve:

- Can print pdf or txt, I only tested txt as escpos raw printing... it's needed to test zpl or txt print.
- tests must be done
- pre-commit get errors, related with qz-tray.js that is the original library, and related with js code and requiremet OpenSSL.
- at this moment you need to write the name of the printer, could be nice to create a widget show local printers and select one (js code is quite simple).

@chrisandrewmann changes:

- Made the user_id not required on printing.report.qz.tray - This way you can set a default for ALL users
- Updated to support new OWL action report handler and frontend logic
- Added ability to specify a remote server location (IP) for the printer, so it doesn't have to work only locally
- Tested with both PDF and ZPL using "Virtual ZPL Printer" - All looks good

### CODE REVIEW

**Comment by miquelalzanillas** [comment]
Hello @chrisandrewmann , could you please re-open this? I'm interested in to work on this for v18 using it as dependency in a new module for qz pos printing.

**Comment by chrisandrewmann** [comment]
> Hello @chrisandrewmann , could you please re-open this? I'm interested in to work on this for v18 using it as dependency in a new module for qz pos printing.

Hi @miquelalzanillas that's great to hear. I've actually migrated it to V17, 18 and 19 for myself but gave up trying to get it into OCA. 
Let's connect and discuss how to best collaborate.

**Comment by miquelalzanillas** [comment]
Hi @chrisandrewmann ,

Sure! Let me know which way you prefer.

Why did you give up on getting the migrations into OCA?

Yesterday, I almost finished migrating to v18. I've had some issues handling plain JS in v18.

Now I have the PR almost ready (following OCA conventions, that was not easy :) ) to add the module directly to v18, based on this PR.

But let's connect or let me know which way you prefer.

**Comment by chrisandrewmann** [comment]
> Hi @chrisandrewmann ,
> 
> Sure! Let me know which way you prefer.
> 
> Why did you give up on getting the migrations into OCA?
> 
> Yesterday, I almost finished migrating to v18. I've had some issues handling plain JS in v18.
> 
> Now I have the PR almost ready (following OCA conventions, that was not easy :) ) to add the module directly to v18, based on this PR.
> 
> But let's connect or let me know which way you prefer.

Feel free to email: chris.mann@openusersystems.com
We could have a call and discuss.
I'd be happy to package up and send you all my code and let you incorporate what you need.

**Comment by smartobc-stephen** [comment]
@chrisandrewmann @miquelalzanillas I would also like to work on an open source solution. Do you guys have a public repo I could work on? Is the work stalled? What do you need help with?

**Comment by miquelalzanillas** [comment]
Hello @smartobc-stephen , 

I'm working on an important refactor in this repository in order to add QZTray support mantaining modularity.
Roadmap:

- Extract 'CUPS' support from 'base_report_to_printer' in to a sepparate module ('base_report_to_printer_cups') :heavy_check_mark: 
- Add new module 'base_report_to_printer_qz' to add QZTray support. :heavy_check_mark: 
- Currently in progress adding QZTray support for POS receipt printer adding new module 'pos_printing_qz' that depends on this repository. :x: 

All this changes will be proposed in a migration to v19 pull request that I have almost ready. 

I will mention here [MIG] pull request once created.

Here is the current progress in a v18.

https://github.com/APSL/report-print-send/tree/18.0-add-base_report_to_qz

**Comment by chrisandrewmann** [comment]
> Hello @smartobc-stephen ,
> 
> I'm working on an important refactor in this repository in order to add QZTray support mantaining modularity. Roadmap:
> 
> * Extract 'CUPS' support from 'base_report_to_printer' in to a sepparate module ('base_report_to_printer_cups') ✔️
> * Add new module 'base_report_to_printer_qz' to add QZTray support. ✔️
> * Currently in progress adding QZTray support for POS receipt printer adding new module 'pos_printing_qz' that depends on this repository. ❌
> 
> All this changes will be proposed in a migration to v19 pull request that I have almost ready.
> 
> I will mention here [MIG] pull request once created.
> 
> Here is the current progress in a v18.
> 
> https://github.com/APSL/report-print-send/tree/18.0-add-base_report_to_qz

@miquelalzanillas that's great to hear that you've taken it on.
Although I can't justify spending time on it at the moment, if it helps I can provide you my V18-V19 migrated code for you to compare to your own for the module. Just reach out to me on email.

**Comment by miquelalzanillas** [comment]
Ok! @chrisandrewmann 

Thanks.

**Comment by smartobc-stephen** [comment]
@miquelalzanillas Thank you for the update. I am not familiar with QZTray, but as I have explained to Chris, I have extensive knowledge developing drivers for Odoo's iot and I also developed a module for point_of_sale that implements fiscal laws of the country where I live. 
I will start looking at the documentation of QZTray then the code and see what I can contribute with, probably tests

**Pull request closed without merging**
