### PR TITLE
[11.0][FIX] requirements.txt: Updated

### PR DESCRIPTION
**Pull request by igallart**
https://github.com/OCA/report-print-send/issues/186

### CODE REVIEW

**Comment by moylop260** [comment]
@pedrobaeza 
Could you check it, please?
Since that you have updated without a properly PR
https://github.com/OCA/report-print-send/commit/6280913bd2241b771edde9e45e18eae7b32291ed

There is not a helpful commit message of “Why” you are using another version or a link with discussion about

**Comment by pedrobaeza** [comment]
That was a leftover of this cleaning for making Travis to work: https://github.com/OCA/report-print-send/commit/93d3727a17fc42c6386bc100962a1a7d0d7b8f67, and I put exactly the same version that was installed manually in Travis, so this must be correct, or ask the original contributor why it put that version there.

**Comment by moylop260** [comment]
FYI runbot is red because of the lib packages `libcups2-dev` was deleted from:
 - https://github.com/OCA/report-print-send/commit/93d3727a17fc42c6386bc100962a1a7d0d7b8f67

But it is required in order to avoid the following error:

```python
[91m  ERROR: Command errored out with exit status 1:
   command: /.repo_requirements/virtualenv/python3.5/bin/python3.5 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_tj8tnh7/pycups/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_tj8tnh7/pycups/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-o33n48of --python-tag cp35
       cwd: /tmp/pip-install-_tj8tnh7/pycups/
  Complete output (12 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'cups' extension
  creating build
  creating build/temp.linux-x86_64-3.5
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -DVERSION="1.9.73" -I/usr/include/python3.5m -I/.repo_requirements/virtualenv/python3.5/include/python3.5m -c cupsmodule.c -o build/temp.linux-x86_64-3.5/cupsmodule.o
  cupsmodule.c:23:23: fatal error: cups/cups.h: No such file or directory
   #include <cups/cups.h>
                         ^
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pycups
```

Shouldn't create a properly PR in order to see the CI working fine before to merge it instead of push directly (even if we have permission to do it, even if it is a small and inoffensive change)?

The direct pushed commits are invisible for CI, contributors and maintainers.
In most cases, an isolated commit pushed directly doesn't have a helpful message or reference of "why"
  - See https://github.com/OCA/report-print-send/commit/6280913bd2241b771edde9e45e18eae7b32291ed without https://github.com/OCA/report-print-send/commit/93d3727a17fc42c6386bc100962a1a7d0d7b8f67 is so complex to trace.

Using a PR you can see a CI red before to merge it and fix it using just one commit in order to have full context.
Using a PR sends a notification to all about changing in order to give our opinion (is not this community?) or just be aware.

What do you think OCA board?
cc @rafaelbn @max3903 @nhomar @jgrandguillaume @gurneyalex

**Comment by pedrobaeza** [comment]
@moylop260 I'm not going to do that because I'm doing administrative changes all days and it's not operative. Mistakes happen. They are fixed and everything continues without problem. If you don't like it, I invite you to take my role and provide support across entire OCA to see how much time you need to spend with your proposal.

Said that, if you are not going to fix it, I will, but with direct commit.

**Comment by moylop260** [comment]
Fixed from https://github.com/OCA/report-print-send/commit/f0bb2c96b7c6649816335aace00fbab7ab0dcadf

Thanks @igallart

**Pull request merged**
