### PR TITLE
FIX: print with copies and installed printer_tray module

### PR DESCRIPTION
**Pull request by msteinfeld-intero**
Added new Argument to printer_tray also. #46

### CODE REVIEW

**Comment by guewen** [comment]
:+1: 
Thanks!

**Comment by msteinfeld-intero** [comment]
runbot check failed cause of cups.
where should i have to sign cla?

**Comment by guewen** [comment]
See this page for the CLA: https://odoo-community.org/page/cla

**Comment by oihane** [comment]
:+1: Same issue found in client.

**Comment by pedrobaeza** [comment]
:+1:

**Comment by pedrobaeza** [comment]
@msteinfeld, I have merged this without checking CLA, and I see that you haven't signed. Can you please sign it? It's very easy to do. On contrary, we will need to revert this.

**Comment by msteinfeld-intero** [comment]
@pedrobaeza sorry for the delay. Will sign today in space of work. promised

**Comment by msteinfeld-intero** [comment]
@pedrobaeza sent

**Pull request merged**
