### PR TITLE
[Usability] Auto-add Administrator user to the Print group

### PR DESCRIPTION
**Pull request by alexis-via**
This PR will automatically add the Administrator user to the Print group, which is quite convenient. A lot of modules do that !
It also cleans up the XML code by removing the ugly "&quot;&quot;&quot;"

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by guewen** [comment]
Did  you saw? https://github.com/OCA/report-print-send/pull/18

**Comment by pedrobaeza** [comment]
I think they are complementary, doesn't it?

**Comment by guewen** [comment]
Yes. But the changes on the quotes will conflict.

:+1:

**Comment by pedrobaeza** [comment]
Yeah, I see. A rebase of the PR that will be merged after can serve.

**Comment by alexis-via** [comment]
@guewen I was not aware of #18 initially, but I was impacted by the bug this morning and found your PR to fix it thanks to your comment here ! :)
Yes, i'll rebase it after the merge. The priority is to merge the bugfix, not this PR !

**Comment by pedrobaeza** [comment]
You can rebase now

**Comment by alexis-via** [comment]
thanks @pedrobaeza 
I tried a rebase (it's the first time I do that I think), but my push is rejected by github for some obscure reasons. I'll try again later, when I have time...

**Comment by pedrobaeza** [comment]
You have to force it with -f option.

**Comment by alexis-via** [comment]
@pedrobaeza Thanks for the tip. It seems that my rebase is OK now.

**Comment by pedrobaeza** [comment]
:+1:

**Comment by guewen** [comment]
:+1:

**Pull request merged**
