### PR TITLE
[8.0] [FIX]: change signature of methods print_document & get_pdf for 8.0 api

### PR DESCRIPTION
**Pull request by anthony-muschang**
It is currently not possible to do the following calls:

``` python
report_model = self.env['report']
invoice_model = self.env['account.invoice']

invoices = invoice_model.search([])
report_model.get_pdf(invoices, 'account.report_invoice')
report_model.print_document(invoices, 'account.report_invoice')
```

The signature of the methods print_document & get_pdf have been modified in order to be able to call them from 8.0 api.

I use the same signature as seen in the standard 'report' module:
https://github.com/odoo/odoo/blob/453b373a685d652bc8e542284a0da899ce5ffccd/addons/report/models/report.py#L277

### CODE REVIEW

**Comment by guewen** [comment]
Makes sense.
Is the change necessary for `get_pdf` since it is already done in the core?

**Comment by anthony-muschang** [comment]
Yes. Because the get_pdf of base_report_to_printer will be call first.

**Comment by guewen** [comment]
Indeed, but I thought the decorators were inherited and thus it was not necessary to repeat them. It is maybe not true for `@api.v7` and `@api.v8`.
:+1:

**Comment by pedrobaeza** [comment]
Please make it the other way and let the main method to be @api.v8, so the migration to v9 will be smoother.

**Comment by yvaucher** [comment]
:+1:

**Comment by lmignon** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Don't merge until my comment is reviewed

**Comment by guewen** [comment]
@pedrobaeza considering that:
- the base model is not migrated
- the `report` model is a mess to use with the new API because in this model `ids` are not `ids` of the `report` model but of the model the report is working on
- this is a bugfix

I find it well to leave it like that until the base model is migrated

**Comment by anthony-muschang** [comment]
@guewen :+1:

**Comment by yvaucher** [comment]
agreed with @guewen for bug fix I prefer simple changes instead of trying to push other improvement changes such as API refactoring

**Comment by pedrobaeza** [comment]
OK, let's keep it as is

**Pull request merged**
