### PR TITLE
[MIG][16.0] base_report_to_printer

### PR DESCRIPTION
**Pull request by glitchov**
Migration from 15.0

### CODE REVIEW

**Review by lmignon — APPROVED** [review]
LGTM  (Code review)

**Review by sebalix — APPROVED** [review]

**Comment by alexis-via** [comment]
This PR blew up all generation of reports. So please come and approve the PR to fix this mess: https://github.com/OCA/report-print-send/pull/316

**Comment by alexis-via** [comment]
The views were not properly ported in this PR. It fixed them in another PR: https://github.com/OCA/report-print-send/pull/322 Please come and approve it to finalize the v16 migration!

**Pull request merged**
