### PR TITLE
[12.0][MIG] remote_report_to_printer

### PR DESCRIPTION
**Pull request by jarroyomorales**
Standard migration to 12.0 of remote_report_to_printer.

### CODE REVIEW

**Review by etobella — APPROVED** [review]
LGTM

**Review by marcelsavegnago — APPROVED** [review]

**Comment by marcelsavegnago** [comment]
cc @marcos-mendez

**Comment by etobella** [comment]
@OCA/tools-maintainers I think this is ready to merge :smile:

**Pull request merged**
