### PR TITLE
[9.0][MIGR] base_report_to_printer migr

### PR DESCRIPTION
**Pull request by valentinthirion**

### CODE REVIEW

**Comment by valentinthirion** [comment]
@tafaRU can U review this, please?

**Comment by tafaRU** [comment]
@valentinthirion travis build is red, please see https://travis-ci.org/OCA/report-print-send/jobs/164890630 and try to fix the errors highlighted there. Feel free to ask me if you need some help.

**Comment by lasley** [comment]
Hi @valentinthirion - thanks for the submission, but did you see #52? I am closing this PR as the previous one is passing build and has precedence. Please let me know if you have a reason as to why this should supersede mine & I'll be happy to re-eval/re-open. Otherwise, I would appreciate some reviews on the pre-existing for merge.

**Comment by tafaRU** [comment]
@lasley it was my fault, yesterday during the OCA Sprint @valentinthirion asked to help him to create his first PR but I forgot to check the existing PRs, before to do it!

Anyway, in this way @valentinthirion have learned a new thing and is now able to contributo to OCA :wink

**Comment by pedrobaeza** [comment]
To be noticed is that there's one opened issue per repository to track the assignment of the migration of each module, even before it will be started, so that you can avoid duplicated efforts.

**Pull request closed without merging**
