### PR TITLE
[12.0] ADD printer_zpl2_browser_print

### PR DESCRIPTION
**Pull request by eLBati**
Allow to print ZPL labels directly from web browser, using printers installed in client device.

See [Zebra Browser Print](https://www.zebra.com/us/en/products/software/barcode-printers/link-os/browser-print.html)

### CODE REVIEW

**Comment by eLBati** [comment]
@sylvain-garancher @fmdl @JosDeGraeve what do you think?

**Review by gurneyalex — COMMENTED** [review]
Can you provide information about the licence of the JS library that is shipped with this addon?

**Comment by eLBati** [comment]
Hi @gurneyalex , thank you for pointing this out.
No license information is provided with the library, but I found this
https://www.zebra.com/us/en/support-downloads/support-eula/browser-print-eula-javascript.html

This is not compatible with OCA, right?

**Comment by gurneyalex** [comment]
@eLBati I confirm this is not compatible (no right to modify the code of this file). I'm therefore closing this PR. Sorry about this.

**Pull request closed without merging**
