### PR TITLE
[ADD] label_zpl2 and make printer_zpl2 depend to it

### PR DESCRIPTION
**Pull request by etobella**
I have detected that `printer_zpl2` depends on `base_report_to_printer` but I think it may not be the best options, because you could require zpl2 but not use the module of printers.

This PR splits the module in two. The first is `label_zpl2`, that creates the models and allows to render the labels. The second is `printer_zpl2` that will inherit from the first.

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
@sylvain-garancher As the original author of this module, it would be best if you can tell us if you're good with this proposal. Can you help us?

**Comment by max3903** [comment]
@etobella I am not sure to understand why you would split. If you create ZPL2 labels, I would assume it's to print them on a ZPL2 printers, no? Can you explain your use case? Do you plan to use one module and not the other?

**Comment by Garamotte** [comment]
Like @max3903, I don't understand the usecase, but I'm not against splitting the module if it contains several independant features, as long as everything works after the split :)

However, I think that the split should wait for the next Odoo version.
Some people may have modules depending on this version, and your split changes many things (xml_ids of the models, views, menus, etc.) that can break custom modules inheriting from this one.

**Comment by etobella** [comment]
Well, I am using odoo integrated with another software and all the printing queres are managed from the other software.
All data is stored on odoo, so I tried to generate the labels on odoo and use the printing queues from the other software. I am currently using it in order to print complex templates and I would like to use it also for labels.

**Comment by max3903** [comment]
@etobella Thanks for the explanation. It makes more sense now.

I don't mind merging this in v11 as far as the version is bumped accordingly.

**Comment by max3903** [comment]
@etobella Can you split the pull request to have one per module? Thanks.

**Comment by etobella** [comment]
I have divided the module in two. (#150)

**Review by max3903 — APPROVED** [review]

**Comment by JordiBForgeFlow** [comment]
@sylvain-garancher @alnslang The module was migrated by you to 11.0 just two months ago. I think that it is important to coordinate the changes with you. But I do not expect many other people to use the modules. The module is not yet available in the app store for 11.0 https://www.odoo.com/apps/modules/10.0/printer_zpl2/

Also, if a person fetched all the repo the update will run correctly, and will install label_zpl2

**Comment by pedrobaeza** [comment]
More than to use it, to extend it, so the changes on XML-IDs won't affect. I think this can be very valuable for these regular contributors in this version (they can't wait for next version), and with a very little cost.

**Comment by etobella** [comment]
I cancel the PR as it will not be merged for the related problems found for migration.

**Pull request closed without merging**
