### PR TITLE
[IMP] base_report_to_printer: archive printers

### PR DESCRIPTION
**Pull request by jarroyomorales**
Allow to archive printers.

@etobella

### CODE REVIEW

**Review by bodedra — APPROVED** [review]

**Review by etobella — APPROVED** [review]

**Comment by etobella** [comment]
Can you prepare the cherry-pick for 13.0 please @jarroyomorales

**Comment by pedrobaeza** [comment]
Shouldn't this be taken into account when updating printers from server (with `active_test=False` or similar for doing the match)?

**Review by bealdav — APPROVED** [review]

**Comment by jarroyomorales** [comment]
@pedrobaeza After doing some testing I see it is necessary to add the `active_test=False` if we want to keep the archived printed updated. Thank you!

**Pull request merged**
