### PR TITLE
[16.0][MIG] base_report_to_label_printer

### PR DESCRIPTION
**Pull request by glitchov**
Migration from 14.0
This module makes it possible to print specific reports to a label printer that is configured on the user.

### CODE REVIEW

**Review by lmignon — APPROVED** [review]
LGTM (Code review)

**Comment by IT-Ideas** [comment]
@glitchov , @lmignon should the PR still be reviewed? It has been automatically closed.
Otherwise LGTM 🙂

**Comment by rousseldenis** [comment]
@OCA/tools-maintainers Could you reopen this one ?

**Review by rousseldenis — APPROVED** [review]
Code review.

Works for months in production

**Pull request merged**
