### PR TITLE
Add missing default oca icons

### PR DESCRIPTION
**Pull request by yvaucher**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by lmignon** [comment]
:+1:  @yvaucher A nice to have should be to also fix the last remaining pep8 issues :smirk:

**Comment by yvaucher** [comment]
@lmignon I fixed it in a separated PR: https://github.com/OCA/report-print-send/pull/32

**Comment by yvaucher** [comment]
to merge carefully as modules have dependency on cups it could be another issue with static folders

**Comment by yvaucher** [comment]
This is on branch 8.0, thus let's close it.

**Pull request closed without merging**
