### PR TITLE
[16.0][FIX] printing_simple_configuration: add company_id to printer

### PR DESCRIPTION
**Pull request by mourad-ehm**

### CODE REVIEW

**Review by bealdav — APPROVED** [review]
Thanks for this fix

**Review by hparfr — APPROVED** [review]

**Review by pedrobaeza — DISMISSED** [review]
Please use proper commit message: https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#commit-message

**Comment by mourad-ehm** [comment]
Thanks @pedrobaeza, I fix it

**Comment by pedrobaeza** [comment]
The change to `sale_stock` may be heavy, but being a niche module, I'm not opposing to it.

/ocabot merge minor

**Pull request merged**
