### PR TITLE
[FIX] 9.0 Issue#63 printing now working

### PR DESCRIPTION
**Pull request by auphofBSF**
missing 1st parameter (rec_id) on get_pdf method

### CODE REVIEW

**Review by moylop260 — APPROVED** [review]
Thanks

**Review by RoelAdriaans — APPROVED** [review]
Patch works, tested with 9.0. 

Maybe rebase the commits into one commit?
4 commits for a one line change is a bit much maybe.

**Comment by Garamotte** [comment]
LGTM (didn't test).
A unit test would be nice ;)

**Comment by lasley** [comment]
Hmmm this looks to already be [fixed on 9.0](https://github.com/OCA/report-print-send/blob/9.0/base_report_to_printer/models/report.py#L15). @sylvain-garancher can you confirm?

**Comment by Garamotte** [comment]
Yes https://github.com/OCA/report-print-send/pull/77 replaced this PR.
This one addressed only the missing parameter issue, instead of really fixing the bug.

**Pull request closed without merging**
