### PR TITLE
[FIX] printer_zpl2: typo external_dependencies

### PR DESCRIPTION
**Pull request by sbidoul**

### CODE REVIEW

**Comment by sbidoul** [comment]
@sylvain-garancher hopefully the travis error is unrelated.

**Comment by sbidoul** [comment]
@ThomasBinsfeld

**Review by ThomasBinsfeld — APPROVED** [review]

**Review by Garamotte — APPROVED** [review]

**Comment by Garamotte** [comment]
I think the `.travis.yml` should be updated to fix the Travis issue.

**Review by pedrobaeza — APPROVED** [review]
Error is unrelated

**Pull request merged**
