### PR TITLE
[14.0][FIX] base_report_to_printer: Don't use safe_eval as module / Add text print

### PR DESCRIPTION
**Pull request by rousseldenis**
Adds:

- [x] Don't use safe_eval as module (Exception raised) introduced there https://github.com/OCA/report-print-send/pull/261 @gurneyalex 
- [x] Add a text printing feature
- [x] Add tests for text printing

### CODE REVIEW

**Comment by OKT96** [comment]
@rousseldenis An error still occurs during a print:

```
Traceback (most recent call last):
  File "/opt/odoo/odoo_ee/src/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo_ee/src/odoo/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: Module <module 'time' (built-in)> can not be used in evaluation contexts

Prefer providing only the items necessary for your intended use.

If a "module" is necessary for backwards compatibility, use
`odoo.tools.safe_eval.wrap_module` to generate a wrapper recursively
whitelisting allowed attributes.

Pre-wrapped modules are provided as attributes of `odoo.tools.safe_eval
```

To fix this we need to pass the time module into the safe_eval context:

```python
from odoo.tools.safe_eval import safe_eval, time
```

**Comment by rousseldenis** [comment]
> @rousseldenis An error still occurs during a print:
> 
> ```
> Traceback (most recent call last):
>   File "/opt/odoo/odoo_ee/src/odoo/odoo/http.py", line 640, in _handle_exception
>     return super(JsonRequest, self)._handle_exception(exception)
>   File "/opt/odoo/odoo_ee/src/odoo/odoo/http.py", line 316, in _handle_exception
>     raise exception.with_traceback(None) from new_cause
> TypeError: Module <module 'time' (built-in)> can not be used in evaluation contexts
> 
> Prefer providing only the items necessary for your intended use.
> 
> If a "module" is necessary for backwards compatibility, use
> `odoo.tools.safe_eval.wrap_module` to generate a wrapper recursively
> whitelisting allowed attributes.
> 
> Pre-wrapped modules are provided as attributes of `odoo.tools.safe_eval
> ```
> 
> To fix this we need to pass the time module into the safe_eval context:
> 
> ```python
> from odoo.tools.safe_eval import safe_eval, time
> ```

Ok, I see but the correct solution is:

`from time import time`

I did it in a separate commit here

**Comment by OKT96** [comment]
hi @rousseldenis will this fix be merged soon?

**Comment by rousseldenis** [comment]
@OCA/core-maintainers

**Comment by gdgellatly** [comment]
@rousseldenis I think this needs a rebase to resolve a merge conflict. FWIW I've been using in production for 3 months without issue to resolve the safe_eval issue this addresses.

**Comment by rousseldenis** [comment]
@gdgellatly Done

**Review by gdgellatly — APPROVED** [review]
Have used in production for 3 months where safe_eval required and text reports are generated (although not to a printer). Everything works fine, plus code review.

**Pull request merged**
