### PR TITLE
[WIP][13.0][MIG] printer_zpl2 migration

### PR DESCRIPTION
**Pull request by schout-it**

### CODE REVIEW

**Comment by schout-it** [comment]
waiting to rebase after #181 is merged to allow full testing

**Comment by okuryan** [comment]
@schout-it , are you going to continue to work on migration?

**Comment by AaronHForgeFlow** [comment]
Hi @schout-it I did the migration of this module in my fork. If you agree and you are not going to continue working on this I will create a separate Pull request to this repo. In other case, if you agree I will create a PR to your branch.

**Comment by dynapps** [comment]
@AaronHForgeFlow  
I'll close this one, and you can create a new pull request, been hectic lately

**Comment by schout-it** [comment]
@AaronHForgeFlow 
I'll close this one, so you can create a new pull request.
Been hectic lately and haven't been able to work further on refactoring the code for flake8 and black

**Comment by AaronHForgeFlow** [comment]
All right. Thanks for the fast answer.

**Comment by fmdl** [comment]
@schout-it I have migrate this module in V12, I have plan to add button on label component to change quickly the position of component please find my PR for V12 here : https://github.com/OCA/report-print-send/pull/205

**Pull request closed without merging**
