### PR TITLE
[13.0][MIG] base_report_to_printer_mail

### PR DESCRIPTION
**Pull request by jarroyomorales**
Standard migration of `base_report_to_printer_mail` to v13.

@etobella  @jimhoefnagels @rven

### CODE REVIEW

**Review by etobella — APPROVED** [review]
LGTM :+1: No major changes

**Comment by etobella** [comment]
@rven Maybe you would like to check it :wink:

**Review by fshah-initos — APPROVED** [review]
No major change. LGTM

**Comment by fshah-initos** [comment]
It seems that PR is ready to merge. can someone please merge this?

**Comment by fshah-initos** [comment]
Can this PR be merged?

**Comment by fshah-initos** [comment]
Hi @etobella It would be great if you can merge the PR.

**Comment by etobella** [comment]
No, I can't, it is better to ask directly to the responsible PSC team (you can check it on https://odoo-community.org/psc-teams)

In this case @OCA/tools-maintainers

**Pull request merged**
