### PR TITLE
[14.0] Add Module base_report_to_label_printer

### PR DESCRIPTION
**Pull request by simahawk**
replaces #283

### CODE REVIEW

**Review by sebalix — APPROVED** [review]

**Comment by sebalix** [comment]
Already reviewed and approved on the previous PR, so merging.
/ocabot merge nobump

**Comment by simahawk** [comment]
/ocabot merge nobump

bah pre-commit env setup is failing randomly

**Comment by simahawk** [comment]
the bot seems to be drunk... :sweat_smile: 

/ocabot merge nobump

**Comment by simahawk** [comment]
@sbidoul could you check what's wrong here or tell me how can I find it?

**Comment by sbidoul** [comment]
@simahawk in the bot log and in sentry: `setup/base_report_to_label_printer/odoo/addons must contain exactly one installable Odoo addon dir, found []`. Could it be `setup/base_report_to_label_printer/odoo/addons/base_report_to_label_printer` is a regular file instead of a symlink? I've seen that happening from people working on Windows.

**Comment by sbidoul** [comment]
Not sure why the bot does not report the error here, though.

**Comment by sebalix** [comment]
@sbidoul @simahawk I regenerated the `setup` folder of this module with pre-commit, git status was showing `T` (meaning the file type has changed, so it's probably what you were saying @sbidoul ).
Trying again:
/ocabot merge nobump

**Comment by sbidoul** [comment]
BTW I still have plans to replaces those setup.py and symlinks with a `pyproject.toml` in each addon directory.

**Pull request merged**
