### PR TITLE
[PEP8] + latest MQT template

### PR DESCRIPTION
**Pull request by laetitia-gangloff**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please fix also Travis file to have latest changes in MQT

**Comment by laetitia-gangloff** [comment]
Ok, I updated pep8 of the other modules.
I also updated README.md and .travis.yml to the last MQT template.

I think now, it is green \o/

**Comment by pedrobaeza** [comment]
Thank you very much!

:+1:

**Comment by pedrobaeza** [comment]
Fast-tracking as this makes green the branch.

**Comment by lmignon** [comment]
:+1:

**Comment by laetitia-gangloff** [comment]
@pedrobaeza thank you !

**Comment by lmignon** [comment]
after speedy gonzales, speedy pedro :smirk: 
image

**Comment by pedrobaeza** [comment]
hahaha

**Pull request merged**
