### PR TITLE
[9.0][IMP] Change version to allow install in Ubuntu 16.04+

### PR DESCRIPTION
**Pull request by igallart**
The version 1.9.66 is very old, and is not possible install in Ubuntu 16.04. Presumably, in future versions either.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
We told about not blocking versions, or at least put `>=`, isn't it, @sylvain-garancher ?

**Comment by igallart** [comment]
I do not know if higher versions will work. For me no problem.

**Comment by sbidoul** [comment]
Yes please no pinned versions in requirements.txt. Use `>=` if you know the minimum required version.

**Comment by Garamotte** [comment]
I don't know why this module is pinned to version 1.9.66, but I can confirm that versions below 1.9.68 cannot be installed on Ubuntu 16.04, so `pycups>=1.9.68` seems good, as [we shouldn't pin versions in `requirements.txt`](https://github.com/OCA/maintainer-quality-tools/issues/494).

I personnally always use the latest version without any issue (which is also very old).

**Review by yvaucher — APPROVED** [review]

**Pull request merged**
