### PR TITLE
[12.0][ADD] base_report_to_printer: Print attachments wizard

### PR DESCRIPTION
**Pull request by KARIZMA-CONSEIL**

### CODE REVIEW

**Comment by sebalix** [comment]
Hi @KARIZMA-CONSEIL,
Regarding your PRs, you have to keep the commit history when you migrate code from one version to another.
You will find some information here: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0 (to adapt depending on your case/branch from where commits are coming from).

I put here the link of the original PR for others reviewers: https://github.com/OCA/report-print-send/pull/214

**Comment by KARIZMA-CONSEIL** [comment]
> Hi @KARIZMA-CONSEIL,
> Regarding your PRs, you have to keep the commit history when you migrate code from one version to another.
> You will find some information here: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0 (to adapt depending on your case/branch from where commits are coming from).
> 
> I put here the link of the original PR for others reviewers: #214

Hi Sébastien,

Thank you for the link, i followed the instruction but i got stuck in the command below:

`git format-patch --keep-subject --stdout origin/12.0..origin/9.0 -- base_report_to_printer | git am -3 --keep`

I got this error : `fatal: bad revision 'origin/12.0..origin/9.0'`

**Comment by sebalix** [comment]
Yes you have to adapt the command line to retrieve commits from where they are: at the top of the PR https://github.com/OCA/report-print-send/pull/214 you can see that the original branch is `grindtildeath/9.0-add-print_attachment_wizard`, so in your local copy of the repository you have to add the remote `grindtildeath`:

    $ git remote add grindtildeath

Then fetch the branch containing the commits you are interested in:

    $ git fetch grindtildeath 9.0-add-print_attachment_wizard

From there you'll be able to replay the commits on your `12.0-add-print_attachment_wizard` branch:

    $ git format-patch --keep-subject --stdout origin/12.0..grindtildeath/9.0-add-print_attachment_wizard -- base_report_to_printer | git am -3 --keep

Or as there few commits to port (4 here), you could cherry-pick them one by one if you prefer (`git cherry-pick COMMITHASH`). There are chances that some conflicts appear, you'll have to resolve them. The important thing here is to keep the history and thus preserve the copyright of the original work. If really there is too much difference/adaptations needed between 9.0 and 12.0, it could deserve a whole rewrite and thus a new commit of your own, but it's a solution of last resort.

**Comment by KARIZMA-CONSEIL** [comment]
Thank you for the instructions. I cherry-picked all the 4 commits in a new MR https://github.com/OCA/report-print-send/pull/223

**Comment by yvaucher** [comment]
Superseeded by #222

**Pull request closed without merging**
