### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by Lencof**

### CODE REVIEW

**Comment by etobella** [comment]
@Lencof What is this?

**Comment by Lencof** [comment]
What?

**Comment by Lencof** [comment]
update

**Comment by etobella** [comment]
This is not needed, as this already come from odoo...

**Comment by Lencof** [comment]
a little editing and that's it

**Comment by gurneyalex** [comment]
I don't see what you are trying to achieve here. Closing.

**Pull request closed without merging**
