### PR TITLE
[14.0][IMP] base_report_to_printer: Add test page printing

### PR DESCRIPTION
**Pull request by rousseldenis**

### CODE REVIEW

**Review by fmdl — APPROVED** [review]

**Review by flotho — APPROVED** [review]
good idea
LGTM

**Comment by rousseldenis** [comment]
@fmdl @flotho I've added Raw test page printing.

**Review by fmdl — APPROVED** [review]

**Review by flotho — APPROVED** [review]
LGTM, code review

**Comment by andreampiovesana** [comment]
merge?

**Pull request merged**
