### PR TITLE
[13.0][MIG] printer_zpl2

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
Supersedes #204

### CODE REVIEW

**Comment by fmdl** [comment]
@AaronHForgeFlow please this commit here for quick move (if not it doesn't work correctly with labelary mode) : https://github.com/OCA/report-print-send/pull/205
Thx

**Comment by MiquelRForgeFlow** [comment]
@fmdl done

**Comment by AaronHForgeFlow** [comment]
Nice improvement! :clap:

**Comment by MiquelRForgeFlow** [comment]
It's green :green_apple: , ready to review and merge.

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by LoisRForgeFlow — APPROVED** [review]
Code review :+1:

**Review by etobella — APPROVED** [review]
LGTM :+1:

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by DonatasV — APPROVED** [review]
Tested functionally, works just fine

**Review by Du-ma — APPROVED** [review]
LGTM ✌️

**Review by fla-subteno-it — APPROVED** [review]

**Comment by fla-subteno-it** [comment]
@pedrobaeza could you merge ? thanks

**Comment by pedrobaeza** [comment]
Merging due to the high number of approvals, but take into account that reviews from non PSC members don't count the same as ones coming from them. Anyway, there are some trusted reviewers here, so:

/ocabot merge nobump

**Pull request merged**
