### PR TITLE
Update copier template 1.15.0

### PR DESCRIPTION
**Pull request by micheledic**
Bump the version of oca template to 1.15.0

### CODE REVIEW

**Comment by micheledic** [comment]
@pedrobaeza can you help me ? the pre-commit is in error.

**Comment by pedrobaeza** [comment]
It seems there's a corrupted translation file in `base_report_to_printer/i18n/es.po:956`

https://github.com/OCA/report-print-send/actions/runs/5680001918/job/15393243458?pr=334#step:7:70

Can you please fix it?

**Comment by micheledic** [comment]
> It seems there's a corrupted translation file in `base_report_to_printer/i18n/es.po:956`
> 
> https://github.com/OCA/report-print-send/actions/runs/5680001918/job/15393243458?pr=334#step:7:70
> 
> Can you please fix it?

I have not changed It in my commit. Should i commit the change on that .po file in this PR or should i create a different PR and than rebase this?

**Comment by pedrobaeza** [comment]
No, of course it's not your fault. It's just something hidden that has arisen now that the pre-commit is checking more things. Please fix it adding a commit in this PR.

**Comment by micheledic** [comment]
> No, of course it's not your fault. It's just something hidden that has arisen now that the pre-commit is checking more things. Please fix it adding a commit in this PR.

Done! Tests ok... When this PR Is merged i can rebase my other PR

**Review by yajo — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Thanks!

/ocabot merge patch

**Comment by pedrobaeza** [comment]
Ouch, overlap! I have cancelled my GH actions for letting the other ones to act.

**Pull request merged**
