### PR TITLE
[MIG] base_report_to_printer_mail: Migration to 15.0

### PR DESCRIPTION
**Pull request by matiasperalta1**

### CODE REVIEW

**Comment by igh-odoo** [comment]
Hi,

great work! We are really looking forward to the 15.0 migration.

I installed the current version from the PR today and what I noticed was that users that do not have the Employees/Officer role are not allowed to edit their own profile any more:

The requested operation can not be completed due to security restrictions.

Document type: Users (res.users)
Operation: read
User: 14
Fields:
- address_home_id (allowed for groups 'Employees / Officer')
- barcode (allowed for groups 'Employees / Officer')
- birthday (allowed for groups 'Employees / Officer')
- certificate (allowed for groups 'Employees / Officer')
- children (allowed for groups 'Employees / Officer')
- country_of_birth (allowed for groups 'Employees / Officer')
- emergency_contact (allowed for groups 'Employees / Officer')
- emergency_phone (allowed for groups 'Employees / Officer')
- employee_bank_account_id (allowed for groups 'Employees / Officer')
- employee_country_id (allowed for groups 'Employees / Officer')
- employee_phone (allowed for groups 'Employees / Officer')
- gender (allowed for groups 'Employees / Officer')
- identification_id (allowed for groups 'Employees / Officer')
- km_home_work (allowed for groups 'Employees / Officer')
- marital (allowed for groups 'Employees / Officer')
- passport_id (allowed for groups 'Employees / Officer')
- permit_no (allowed for groups 'Employees / Officer')
- pin (allowed for groups 'Employees / Officer')
- place_of_birth (allowed for groups 'Employees / Officer')
- spouse_birthdate (allowed for groups 'Employees / Officer')
- spouse_complete_name (allowed for groups 'Employees / Officer')
- study_field (allowed for groups 'Employees / Officer')
- study_school (allowed for groups 'Employees / Officer')
- visa_expire (allowed for groups 'Employees / Officer')
- visa_no (allowed for groups 'Employees / Officer')

I think this has to to do something with the module adding fields to the res.users model, hasn't it?

Best regards,
Florian Pose

**Review by cyrilmanuel — APPROVED** [review]
LGTM

**Review by cyrilmanuel — APPROVED** [review]
LGTM

**Comment by sebalix** [comment]
@matiasperalta1 Hello, can you rebase your PR on last 15.0 branch? That could fix the build.

**Comment by oreju** [comment]
Hello @matiasperalta1 , could you check it?

**Comment by nilshamerlinck** [comment]
Hi @oreju you can have a look at https://github.com/OCA/report-print-send/pull/332 that has been rebased

**Pull request closed without merging**
