### PR TITLE
[MIG][14.0] base_report_to_printer

### PR DESCRIPTION
**Pull request by alexis-via**
I included in this migration the active field on printing.printer as per PR https://github.com/OCA/report-print-send/pull/233

### CODE REVIEW

**Comment by CarlosRoca13** [comment]
Please squash the administrative commits and add to requirements.txt the external dependency pycups==1.9.74

**Comment by yajo** [comment]
Would you be so kind to modify the commit message of https://github.com/OCA/report-print-send/pull/239/commits/74209934fe9fb0c20e8f4642cdb1caec5f886028 removing the `@` before my username, so Github stops spamming me? 🙏🏼

**Review by CarlosRoca13 — CHANGES_REQUESTED** [review]
Squash the administrative commits, take care about @Yajo say and review travis

**Comment by pedrobaeza** [comment]
Superseded by #242 with missing comments.

**Pull request closed without merging**
