### PR TITLE
[13.0][IMP] printer_zpl2: add lines in wizard

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Add more abstract options in the wizard to increase extensibility.

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
LGTM

**Comment by MiquelRForgeFlow** [comment]
ping: @rousseldenis

**Comment by MiquelRForgeFlow** [comment]
@rousseldenis can we proceed to merge this before the "github-actions" closes the PR?

**Review by rousseldenis — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]

**Review by LoisRForgeFlow — APPROVED** [review]

**Comment by rousseldenis** [comment]
@OCA/tools-maintainers

**Pull request merged**
